
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOC_CLASS = 21;
  public static final int ITEM = 22;
  public static final int DATE = 8;
  public static final int SUB_TITLE = 12;
  public static final int END = 15;
  public static final int ERROR = 18;
  public static final int SECTION = 5;
  public static final int OPERATOR = 7;
  public static final int BEGIN = 9;
  public static final int MAKE = 20;
  public static final int FUNC = 17;
  public static final int TITLE = 3;
  public static final int EOF = 0;
  public static final int NEWLINE = 11;
  public static final int error = 1;
  public static final int MATHMODE = 13;
  public static final int BODY = 14;
  public static final int PACKAGE = 16;
  public static final int TEXT = 4;
  public static final int NM = 10;
  public static final int VAR = 19;
  public static final int LABEL = 6;
  public static final int BF = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BF",
  "TITLE",
  "TEXT",
  "SECTION",
  "LABEL",
  "OPERATOR",
  "DATE",
  "BEGIN",
  "NM",
  "NEWLINE",
  "SUB_TITLE",
  "MATHMODE",
  "BODY",
  "END",
  "PACKAGE",
  "FUNC",
  "ERROR",
  "VAR",
  "MAKE",
  "DOC_CLASS",
  "ITEM"
  };
}

